### ISSUE TITLE
App picks up incorrect media session

### ISSUE THREAD

**Issue by aero31aero** [IllusionMan1212/lyrics-grabbr#7]
Repeatedly the app has been showing me the current playing song in notification (from Symfonium) but clicking the notification opens the app and it tries to search for the title of the last podcast I played (Antennapod).

Can you please introduce a dropdown to select the media session or maybe allow manual search queries?

**Comment by IllusionMan1212** [comment]
This sounds like a bug with how the app is detecting the last media session (or maybe Antennapod is constantly refreshing its media session?)

I'll take a look and try to replicate this.
Also, Instead of a dropdown for the media sessions, how do you feel about an option to configure a blacklist of apps that lyricsgrabbr won't listen to?

**Comment by aero31aero** [comment]
Ah, similar to how last.fm lets us select which apps to scrobble from? That works too.

I noticed Lyrics Grabber had also tried to find lyrics for a voice message I received on Telegram today, haha. App Whitelist would probably be a better idea than app blacklist, since music players/services are like max 5-6 on most people's devices.
